---
- hosts: databases
  vars: 
    db_packages: # Packages to install for the database service
      - mariadb-server
      - MySQL-python
    db_service: mariadb # Name of database service
    src_file: "http://materials.example.com/task_control/my.cnf.template" # configuration file to install
    dst_file: /etc/my.cnf # location of the installed config file on the managed host

  tasks:
    - name: Install {{ db_packages }} package
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ db_packages }}"
      notify: 
        - start_service

    - name: Download and install {{ dst_file }}
      get_url:
        url: "{{ src_file }}"
        dest: "{{ dst_file }}"
        owner: mysql
        group: mysql
        force: yes
      notify:
        - restart_service
        - set_password

  handlers:
    - name: start_service
      service: 
        name: "{{ db_service }}"
        state: started
    - name: restart_service
      service:
        name: "{{ db_service }}"
        state: restarted  
    - name: set_password
      mysql_user:
        name: root
        password: redhat
