---

allow_duplicates: true

galaxy_info:
  author: Andrew Block
  description: Downloads resources from the Red Hat customer portal
  license: Apache License 2.0
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  galaxy_tags:
  - development
  - packaging
  - system
dependencies: []
  
