# windows-updates.yml

- hosts: windows_domain_controllers,windows_workstations

  tasks:
    - name: Check for missing updates.
      win_updates: state=searched
      register: update_count

    - name: List missing updates
      debug: var=update_count

    #Install missing updates only if at least one is missing
    - block:
        - name: Install Updates
          win_updates:
          register: update_result

        - name: Reboot, if needed.
          win_reboot:
            reboot_timeout: 3600
            shutdown_timeout: 3600
          when: update_result.reboot_required
      when: update_count.found_update_count|int >= 1

    - name: Check for missing updates.
      win_updates: state=searched
      register: update_count

    - name: List missing updates
      debug: var=update_count

# Should we rerun if updates still missing?
