# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.define "webserver01" do |web01|
    web01.vm.box = "jptoto/Windows2012R2"
    web01.vm.hostname = "windows-webserver01"
    web01.vm.communicator = "winrm"
    web01.winrm.username = "vagrant"
    web01.winrm.password = "vagrant"
    web01.vm.network "private_network", ip: "192.168.57.3"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end


  config.vm.define "webserver02" do |web02|
    web02.vm.box = "jptoto/Windows2012R2"
    web02.vm.hostname = "windows-webserver02"
    web02.vm.communicator = "winrm"
    web02.winrm.username = "vagrant"
    web02.winrm.password = "vagrant"
    web02.vm.network "private_network", ip: "192.168.57.4"
    web02.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  config.vm.define "dbserver01" do |db01|
    db01.vm.box = "jptoto/Windows2012R2"
    db01.vm.hostname = "windows-dbserver01"
    db01.vm.communicator = "winrm"
    db01.winrm.username = "vagrant"
    db01.winrm.password = "vagrant"
    db01.vm.network "private_network", ip: "192.168.57.5"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end
end
