---
- name: Delete Azure VM and all associated resources
  hosts: localhost
  connection: local
  tasks:

#  - name: Deallocate the virtual machine
#    azure_rm_virtualmachine:
#      resource_group: myResourceGroup
#      name: myVM
#      allocated: no

  - name: Remove VM and all resources
    azure_rm_virtualmachine:
      resource_group: myResourceGroup
      name: myVM5849
      state: absent
      remove_on_absent:
        - network_interfaces
        - virtual_storage
        - public_ips
