---
- name: Create Azure VM
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ securitygroup_name }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound