---
- name: Delete Azure VM and all associated resources
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

#  - name: Deallocate the virtual machine
#    azure_rm_virtualmachine:
#      resource_group: myResourceGroup
#      name: myVM
#      allocated: no

  - name: Remove VM and all resources
    azure_rm_virtualmachine:
      resource_group: myResourceGroup
      name: myVM
      state: absent
      remove_on_absent:
        - network_interfaces
        - virtual_storage
        - public_ips

  - name: Delete a virtual network
    azure_rm_virtualnetwork:
      name: myVnet
      resource_group: myResourceGroup
      state: absent

  - name: Delete security group
    azure_rm_securitygroup:
      resource_group: myResourceGroup
      name: myNetworkSecurityGroup
      state: absent