---
- name: Create Azure VM
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ vm_name }}"
      vm_size: "{{ vm_size }}"
      admin_username: azureuser
      admin_password: redhat
      ssh_password_enabled: true
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnOtPFN0jYQn/gDB+eltRGMq+xV8r5jUBw144X/nsTA97eCL38C+65TzYL0nCzjkugxAULCbuQQEZMF9OgtXHFGZNZZI0976xfsm5gcvGjh8JHvRnZ5qpWwA7EndAn6ka49dXQ5F3c/Mja8PRpszFu0M/rzXPg/xOQRHK7eNQT3xSafVeK9EcFZPnwGUya53uQv78M+AUimwkfmWwwtspP0uSNXEd99xTC0fdH/Scrp6TlQDoUrKfP9NCZo7i+XTdvrk/p404qogtEZK/upet34HDTxlbeN4SvOFOVUEHGQB1ET5LY3xcpzXpFK47szjV9XD2H9VokTZNza4nlEIVX maks@rhel.mlab.com
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0p4fB/EqQQpq7ECHUIhIQbBLcIoV+ZzQ6pZxplMZNQCxkKM4NpJHuWD63s40mQr9ezBmdaZXsGsMVWGd85UaKif8g7gzYzfhbuLKDXnhSLBMxwToam1OBgBhvL0s0A0YKiXKc/LlsHRDA7bE5HmV96aKoXZbR7Bh4dWGE3JuGn6WIRZ2QUX4aLhF0HpCEo/iJlkPLGcZrAfvLYU/g2XOyuSUM6xpDNxwRLMp7gIaxrtdqVJOCowaiuZDseZduOnDzXscWJaOSmKz5sxfUMO5sm8VnFqnqcMxnEkTcDxPn4V78v4QjSruKdMaEt3vDZNMWSk94M7NWSjUzE4RdqCL3 root@tower.mlab.com

      network_interfaces: "{{ vnic_name }}"
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
