---
- name: Create Azure VM
  hosts: localhost
  connection: local
  gather_facts: False
  
  tasks:

  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resourcegroup_name }}"
      location: "{{ resourcegroup_location }}"