---
- name: Create Azure VM
  hosts: localhost
  connection: local
  gather_facts: False
  
  tasks:

  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resourcegroup_name }}"
      location: "{{ resourcegroup_location }}"

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ virtualnetwork_name }}"
      address_prefixes: "{{ virtualnetwork_address_prefix }}"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ subnet_name }}"
      address_prefix: "{{ subnet_prefix }}"
      virtual_network: "{{ virtualnetwork_name }}"

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resourcegroup_name }}"
      allocation_method: Static
      name: "{{ publicaddress_name }}"
    register: output_ip_address

  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."

  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ securitygroup_name }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound

  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ vnic_name }}"
      virtual_network: "{{ virtualnetwork_name }}"
      subnet: "{{ subnet_name }}"
      public_ip_name: "{{ publicaddress_name }}"
      security_group: "{{ securitygroup_name }}"

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resourcegroup_name }}"
      name: "{{ vm_name }}"
      vm_size: "{{ vm_size }}"
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnOtPFN0jYQn/gDB+eltRGMq+xV8r5jUBw144X/nsTA97eCL38C+65TzYL0nCzjkugxAULCbuQQEZMF9OgtXHFGZNZZI0976xfsm5gcvGjh8JHvRnZ5qpWwA7EndAn6ka49dXQ5F3c/Mja8PRpszFu0M/rzXPg/xOQRHK7eNQT3xSafVeK9EcFZPnwGUya53uQv78M+AUimwkfmWwwtspP0uSNXEd99xTC0fdH/Scrp6TlQDoUrKfP9NCZo7i+XTdvrk/p404qogtEZK/upet34HDTxlbeN4SvOFOVUEHGQB1ET5LY3xcpzXpFK47szjV9XD2H9VokTZNza4nlEIVX maks@rhel.mlab.com
      network_interfaces: "{{ vnic_name }}"
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
