---
# tasks file for network_ospf
- name: IOS Devices
  include_tasks: netconf.yml
  when: ansible_network_os == "ios" and ospf is defined
- name: NX-OS Devices
  include_tasks: nxapi.yml
  when: ansible_network_os == "nxos" and ospf is defined
