---
- name: Configure NETCONF
  tags: [api, netconf]
  ios_config:
    provider: "{{provider}}"
    lines:
      - netconf-yang
      - netconf-yang cisco-odm polling-enable
      - restconf
      - ip http server
      - ip http secure-server

- name: Configure SNMP
  tags: [api]
  ios_config:
    provider: "{{provider}}"
    lines:
      - snmp-server community {{ snmp_ro_community | default('public') }} ro
      - snmp-server community {{ snmp_rw_community | default('private') }} rw

- name: Pause for NETCONF to start
  pause:
    seconds: 45
