# Task file to install the extra packages, update /etc/my.cnf from
# a copy stored on the website, and start mariadb on the managed hosts.
- yum:
    name: "{{ extra_packages }}"
 
- get_url:
    url: "http://materials.example.com/task_control/my.cnf"
    dest: "{{ configure_database_path }}"
    owner: mysql
    group: mysql
    mode: 0644
    # Set SELinux context on the /etc/my.cnf file
    seuser: system_u 
    setype: mysqld_etc_t
    force: yes # Update my.cnf file even if it already exists on the managed host

- service:
    name: "{{ db_service }}"
    state: started
    enabled: true
