---
- hosts: all
  vars: 
    db_package: mariadb-server
    db_service: mariadb
    db_users:
      - db_admin
      - db_user
    configure_database_path: /etc/my.cnf

  tasks:
    - name:
      user:
        name: "{{ item }}"
      with_items: "{{ db_users }}"
      when: inventory_hostname in groups['databases']

    - name: Install the database server
      yum:
        name: "{{ db_package }}"
      when: db_package is defined
