---
- name: App installation
  hosts: windows
  gather_facts: false

  tasks:
    - name: Install application
      win_chocolatey:
        name: "{{ item }}"
        state: "{{ state }}"
      loop: "{{ list_of_packages }}"
