---
- name: Manage applications on Windows machines
  hosts: "{{ variable_host | default('windows_servers') }}"
  gather_facts: false

  tasks:
    - name: Install, remove, update, or reinstall application
      win_chocolatey:
        name: "{{ item }}"
        state: "{{ state }}"
      loop: "{{ list_of_packages }}"
