---
- name: App installation
  hosts: windows
  gather_facts: false
  
  tasks:
    - name: Install notepadplusplus
      win_chocolatey:
        name: notepadplusplus
        state: absent
          
