---
- name: Create user
  hosts: windows
  gather_facts: false
  
  tasks:
    - name: Create a user name maks
      win_domain_user:
        name: "{{ user_name }}"
        password: "{{ password }}"
        state: present
        groups: "{{ groups }}"  
