---

- name: Cisco Wired Campus Design
  hosts: gns3-access
  connection: network_cli
  remote_user: david
  become: yes
  become_method: enable

  tasks:
    - name: Global config settings
      ios_config:
        lines:
          - vtp mode transparent
          - spanning-tree mode rapid-pvst
          - udld enable
          - errdisable recovery cause all
          - port-channel load-balance src-dst-ip
          - ip name-server 8.8.8.8
          - no ip http server
          - ip http secure-server

          - snmp-server community python1 RO
          - snmp-server community python2 RW

          - ntp server 87.81.181.2
          - ntp update-calendar

          - clock timezone PST -8
          - clock summer-time PDT recurring
          - service timestamps debug datetime msec localtime
          - service timestamps log datetime msec localtime

          - "vlan 1,10,20,30,40,50"
          - ip default-gateway 192.168.122.1
          - "ip dhcp snooping vlan 100,101"

          - no ip dhcp snooping information option
          - ip dhcp snooping
          - "ip arp inspection vlan 100,101"
          - spanning-tree portfast bpduguard default


      register: print_output

    -  debug: var=print_output


    - name: IPv6 nd policy
      ios_config:
        parents: ipv6 nd raguard policy HOST_POLICY
        lines:
          - device-role host

      register: print_output

    -  debug: var=print_output
