
---
- name: Manage GNS3 devices
  hosts: gns3-ios
  gather_facts: false
  connection: local

  vars:
    cli:
      username: maks
      password: cisco
      transport: cli

  tasks:
    - name: enable ospf
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0

      register: print_output

    -  debug: var=print_output

- name: Switch specific config
  hosts: S1, S2
  gather_facts: false
  connection: local

  vars:
    cli:
      username: david
      password: cisco
      transport: cli

  tasks:
    - name: Create VLANs
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        lines:
          - vlan 2
          - vlan 3
          - vlan 4
          - vlan 5

      register: print_output

    -  debug: var=print_output
