---
  - name: Save Configurations (IOS)
    hosts: Routers
    connection: local
    
    vars:
      creds:
        username: maks
        password: cisco

    tasks:
      - ios_command:
          provider: "{{ creds }}"
          commands: show run
        register: show_run

      - debug:
          msg: "{{ show_run }}"
