---
  - name: Save Configurations (IOS)
    hosts: Routers
    
    vars:
      username: maks
      password: cisco

    tasks:
      - ios_command:
          commands: show run
        register: show_run

      - debug:
          msg: "{{ show_run }}"
