---
  - name: Save Configurations (IOS)
    hosts: Routers
    connection: local
    
    vars:
      creds:
        username: maks
        password: cisco

    tasks:
      - ios_command:
          provider: "{{ creds }}"
          commands: show run
        register: show_run

      - debug:
          msg: "{{ show_run.stdout[0] }}"
          
      - name: Create target directory
          file: path=CFGS state=directory mode=0777
      
      - copy:
          content: "{{ show_run.stdout[0] }}"
          dest: "CFGS/{{ inventory_hostname }}.txt"
