---
- hosts: S3
  connection: network_cli
  become: yes
  become_method: enable

  tasks:
    - net_vlan:
        state: active
        aggregate:
          - { vlan_id: 2, name: Vl2 }
          - { vlan_id: 3, state: suspend }
          - { vlan_id: 4 }
          - { vlan_id: 5 }
          - { vlan_id: 6 }
          - { vlan_id: 7 }
          - { vlan_id: 8 }
          - { vlan_id: 9 }
          - { vlan_id: 10 }
          - { vlan_id: 11 }
          - { vlan_id: 12 }
          - { vlan_id: 13 }
          - { vlan_id: 14 }
          - { vlan_id: 15 }
          - { vlan_id: 16 }
          - { vlan_id: 17 }
          - { vlan_id: 18 }
          - { vlan_id: 19 }
          - { vlan_id: 20 }
          - { vlan_id: 21 }
          - { vlan_id: 22 }
          - { vlan_id: 23 }
          - { vlan_id: 24 }
          - { vlan_id: 25 }
          - { vlan_id: 26 }
          - { vlan_id: 27 }
          - { vlan_id: 28 }
          - { vlan_id: 29 }
          - { vlan_id: 30 }
          - { vlan_id: 31 }
          - { vlan_id: 32 }
          - { vlan_id: 33 }
          - { vlan_id: 34 }
          - { vlan_id: 35 }
          - { vlan_id: 36 }
          - { vlan_id: 37 }
          - { vlan_id: 38 }
          - { vlan_id: 39 }
          - { vlan_id: 40 }
          - { vlan_id: 41 }
          - { vlan_id: 42 }
          - { vlan_id: 43 }
          - { vlan_id: 44 }
          - { vlan_id: 45 }
          - { vlan_id: 46 }
          - { vlan_id: 47 }
          - { vlan_id: 48 }
          - { vlan_id: 49 }
          - { vlan_id: 50 }
          - { vlan_id: 51 }
          - { vlan_id: 52 }
          - { vlan_id: 53 }
          - { vlan_id: 54 }
          - { vlan_id: 55 }
          - { vlan_id: 56 }
          - { vlan_id: 57 }
          - { vlan_id: 58 }
          - { vlan_id: 59 }
          - { vlan_id: 60 }
          - { vlan_id: 61 }
          - { vlan_id: 62 }
          - { vlan_id: 63 }
          - { vlan_id: 64 }
          - { vlan_id: 65 }
          - { vlan_id: 66 }
          - { vlan_id: 67 }
          - { vlan_id: 68 }
          - { vlan_id: 69 }
          - { vlan_id: 70 }
          - { vlan_id: 71 }
          - { vlan_id: 72 }
          - { vlan_id: 73 }
          - { vlan_id: 74 }
          - { vlan_id: 75 }
          - { vlan_id: 76 }
          - { vlan_id: 77 }
          - { vlan_id: 78 }
          - { vlan_id: 79 }
          - { vlan_id: 80 }
          - { vlan_id: 81 }
          - { vlan_id: 82 }
          - { vlan_id: 83 }
          - { vlan_id: 84 }
          - { vlan_id: 85 }
          - { vlan_id: 86 }
          - { vlan_id: 87 }
          - { vlan_id: 88 }
          - { vlan_id: 89 }
          - { vlan_id: 90 }
          - { vlan_id: 91 }
          - { vlan_id: 92 }
          - { vlan_id: 93 }
          - { vlan_id: 94 }
          - { vlan_id: 95 }
          - { vlan_id: 96 }
          - { vlan_id: 97 }
          - { vlan_id: 98 }
          - { vlan_id: 99 }
          - { vlan_id: 100 }
          - { vlan_id: 101 }
          - { vlan_id: 102 }
          - { vlan_id: 103 }
          - { vlan_id: 104 }
          - { vlan_id: 105 }
          - { vlan_id: 106 }
          - { vlan_id: 107 }
          - { vlan_id: 108 }
          - { vlan_id: 109 }
          - { vlan_id: 110 }
          - { vlan_id: 111 }
          - { vlan_id: 112 }
          - { vlan_id: 113 }
          - { vlan_id: 114 }
          - { vlan_id: 115 }
          - { vlan_id: 116 }
          - { vlan_id: 117 }
          - { vlan_id: 118 }
          - { vlan_id: 119 }
          - { vlan_id: 120 }
          - { vlan_id: 121 }
          - { vlan_id: 122 }
          - { vlan_id: 123 }
          - { vlan_id: 124 }
          - { vlan_id: 125 }
          - { vlan_id: 126 }
          - { vlan_id: 127 }
          - { vlan_id: 128 }
          - { vlan_id: 129 }
          - { vlan_id: 130 }
          - { vlan_id: 131 }
          - { vlan_id: 132 }
          - { vlan_id: 133 }
          - { vlan_id: 134 }
          - { vlan_id: 135 }
          - { vlan_id: 136 }
          - { vlan_id: 137 }
          - { vlan_id: 138 }
          - { vlan_id: 139 }
          - { vlan_id: 140 }
          - { vlan_id: 141 }
          - { vlan_id: 142 }
          - { vlan_id: 143 }
          - { vlan_id: 144 }
          - { vlan_id: 145 }
          - { vlan_id: 146 }
          - { vlan_id: 147 }
          - { vlan_id: 148 }
          - { vlan_id: 149 }
          - { vlan_id: 150 }
          - { vlan_id: 151 }
          - { vlan_id: 152 }
          - { vlan_id: 153 }
          - { vlan_id: 154 }
          - { vlan_id: 155 }
          - { vlan_id: 156 }
          - { vlan_id: 157 }
          - { vlan_id: 158 }
          - { vlan_id: 159 }
          - { vlan_id: 160 }
          - { vlan_id: 161 }
          - { vlan_id: 162 }
          - { vlan_id: 163 }
          - { vlan_id: 164 }
          - { vlan_id: 165 }
          - { vlan_id: 166 }
          - { vlan_id: 167 }
          - { vlan_id: 168 }
          - { vlan_id: 169 }
          - { vlan_id: 170 }
          - { vlan_id: 171 }
          - { vlan_id: 172 }
          - { vlan_id: 173 }
          - { vlan_id: 174 }
          - { vlan_id: 175 }
          - { vlan_id: 176 }
          - { vlan_id: 177 }
          - { vlan_id: 178 }
          - { vlan_id: 179 }
          - { vlan_id: 180 }
          - { vlan_id: 181 }
          - { vlan_id: 182 }
          - { vlan_id: 183 }
          - { vlan_id: 184 }
          - { vlan_id: 185 }
          - { vlan_id: 186 }
          - { vlan_id: 187 }
          - { vlan_id: 188 }
          - { vlan_id: 189 }
          - { vlan_id: 190 }
          - { vlan_id: 191 }
          - { vlan_id: 192 }
          - { vlan_id: 193 }
          - { vlan_id: 194 }
          - { vlan_id: 195 }
          - { vlan_id: 196 }
          - { vlan_id: 197 }
          - { vlan_id: 198 }
          - { vlan_id: 199 }
          - { vlan_id: 200 }
          - { vlan_id: 201 }
          - { vlan_id: 202 }
          - { vlan_id: 203 }
          - { vlan_id: 204 }
          - { vlan_id: 205 }
          - { vlan_id: 206 }
          - { vlan_id: 207 }
          - { vlan_id: 208 }
          - { vlan_id: 209 }
          - { vlan_id: 210 }
          - { vlan_id: 211 }
          - { vlan_id: 212 }
          - { vlan_id: 213 }
          - { vlan_id: 214 }
          - { vlan_id: 215 }
          - { vlan_id: 216 }
          - { vlan_id: 217 }
          - { vlan_id: 218 }
          - { vlan_id: 219 }
          - { vlan_id: 220 }
          - { vlan_id: 221 }
          - { vlan_id: 222 }
          - { vlan_id: 223 }
          - { vlan_id: 224 }
          - { vlan_id: 225 }
          - { vlan_id: 226 }
          - { vlan_id: 227 }
          - { vlan_id: 228 }
          - { vlan_id: 229 }
          - { vlan_id: 230 }
          - { vlan_id: 231 }
          - { vlan_id: 232 }
          - { vlan_id: 233 }
          - { vlan_id: 234 }
          - { vlan_id: 235 }
          - { vlan_id: 236 }
          - { vlan_id: 237 }
          - { vlan_id: 238 }
          - { vlan_id: 239 }
          - { vlan_id: 240 }
          - { vlan_id: 241 }
          - { vlan_id: 242 }
          - { vlan_id: 243 }
          - { vlan_id: 244 }
          - { vlan_id: 245 }
          - { vlan_id: 246 }
          - { vlan_id: 247 }
          - { vlan_id: 248 }
          - { vlan_id: 249 }
          - { vlan_id: 250 }
          - { vlan_id: 251 }
          - { vlan_id: 252 }
          - { vlan_id: 253 }
          - { vlan_id: 254 }
          - { vlan_id: 255 }
          - { vlan_id: 256 }
          - { vlan_id: 257 }
          - { vlan_id: 258 }
          - { vlan_id: 259 }
          - { vlan_id: 260 }
          - { vlan_id: 261 }
          - { vlan_id: 262 }
          - { vlan_id: 263 }
          - { vlan_id: 264 }
          - { vlan_id: 265 }
          - { vlan_id: 266 }
          - { vlan_id: 267 }
          - { vlan_id: 268 }
          - { vlan_id: 269 }
          - { vlan_id: 270 }
          - { vlan_id: 271 }
          - { vlan_id: 272 }
          - { vlan_id: 273 }
          - { vlan_id: 274 }
          - { vlan_id: 275 }
          - { vlan_id: 276 }
          - { vlan_id: 277 }
          - { vlan_id: 278 }
          - { vlan_id: 279 }
          - { vlan_id: 280 }
          - { vlan_id: 281 }
          - { vlan_id: 282 }
          - { vlan_id: 283 }
          - { vlan_id: 284 }
          - { vlan_id: 285 }
          - { vlan_id: 286 }
          - { vlan_id: 287 }
          - { vlan_id: 288 }
          - { vlan_id: 289 }
          - { vlan_id: 290 }
          - { vlan_id: 291 }
          - { vlan_id: 292 }
          - { vlan_id: 293 }
          - { vlan_id: 294 }
          - { vlan_id: 295 }
          - { vlan_id: 296 }
          - { vlan_id: 297 }
          - { vlan_id: 298 }
          - { vlan_id: 299 }
          - { vlan_id: 300 }
          - { vlan_id: 301 }
          - { vlan_id: 302 }
          - { vlan_id: 303 }
          - { vlan_id: 304 }
          - { vlan_id: 305 }
          - { vlan_id: 306 }
          - { vlan_id: 307 }
          - { vlan_id: 308 }
          - { vlan_id: 309 }
          - { vlan_id: 310 }
          - { vlan_id: 311 }
          - { vlan_id: 312 }
          - { vlan_id: 313 }
          - { vlan_id: 314 }
          - { vlan_id: 315 }
          - { vlan_id: 316 }
          - { vlan_id: 317 }
          - { vlan_id: 318 }
          - { vlan_id: 319 }
          - { vlan_id: 320 }
          - { vlan_id: 321 }
          - { vlan_id: 322 }
          - { vlan_id: 323 }
          - { vlan_id: 324 }
          - { vlan_id: 325 }
          - { vlan_id: 326 }
          - { vlan_id: 327 }
          - { vlan_id: 328 }
          - { vlan_id: 329 }
          - { vlan_id: 330 }
          - { vlan_id: 331 }
          - { vlan_id: 332 }
          - { vlan_id: 333 }
          - { vlan_id: 334 }
          - { vlan_id: 335 }
          - { vlan_id: 336 }
          - { vlan_id: 337 }
          - { vlan_id: 338 }
          - { vlan_id: 339 }
          - { vlan_id: 340 }
          - { vlan_id: 341 }
          - { vlan_id: 342 }
          - { vlan_id: 343 }
          - { vlan_id: 344 }
          - { vlan_id: 345 }
          - { vlan_id: 346 }
          - { vlan_id: 347 }
          - { vlan_id: 348 }
          - { vlan_id: 349 }
          - { vlan_id: 350 }
          - { vlan_id: 351 }
          - { vlan_id: 352 }
          - { vlan_id: 353 }
          - { vlan_id: 354 }
          - { vlan_id: 355 }
          - { vlan_id: 356 }
          - { vlan_id: 357 }
          - { vlan_id: 358 }
          - { vlan_id: 359 }
          - { vlan_id: 360 }
          - { vlan_id: 361 }
          - { vlan_id: 362 }
          - { vlan_id: 363 }
          - { vlan_id: 364 }
          - { vlan_id: 365 }
          - { vlan_id: 366 }
          - { vlan_id: 367 }
          - { vlan_id: 368 }
          - { vlan_id: 369 }
          - { vlan_id: 370 }
          - { vlan_id: 371 }
          - { vlan_id: 372 }
          - { vlan_id: 373 }
          - { vlan_id: 374 }
          - { vlan_id: 375 }
          - { vlan_id: 376 }
          - { vlan_id: 377 }
          - { vlan_id: 378 }
          - { vlan_id: 379 }
          - { vlan_id: 380 }
          - { vlan_id: 381 }
          - { vlan_id: 382 }
          - { vlan_id: 383 }
          - { vlan_id: 384 }
          - { vlan_id: 385 }
          - { vlan_id: 386 }
          - { vlan_id: 387 }
          - { vlan_id: 388 }
          - { vlan_id: 389 }
          - { vlan_id: 390 }
          - { vlan_id: 391 }
          - { vlan_id: 392 }
          - { vlan_id: 393 }
          - { vlan_id: 394 }
          - { vlan_id: 395 }
          - { vlan_id: 396 }
          - { vlan_id: 397 }
          - { vlan_id: 398 }
          - { vlan_id: 399 }
          - { vlan_id: 400 }
          - { vlan_id: 401 }
          - { vlan_id: 402 }
          - { vlan_id: 403 }
          - { vlan_id: 404 }
          - { vlan_id: 405 }
          - { vlan_id: 406 }
          - { vlan_id: 407 }
          - { vlan_id: 408 }
          - { vlan_id: 409 }
          - { vlan_id: 410 }
          - { vlan_id: 411 }
          - { vlan_id: 412 }
          - { vlan_id: 413 }
          - { vlan_id: 414 }
          - { vlan_id: 415 }
          - { vlan_id: 416 }
          - { vlan_id: 417 }
          - { vlan_id: 418 }
          - { vlan_id: 419 }
          - { vlan_id: 420 }
          - { vlan_id: 421 }
          - { vlan_id: 422 }
          - { vlan_id: 423 }
          - { vlan_id: 424 }
          - { vlan_id: 425 }
          - { vlan_id: 426 }
          - { vlan_id: 427 }
          - { vlan_id: 428 }
          - { vlan_id: 429 }
          - { vlan_id: 430 }
          - { vlan_id: 431 }
          - { vlan_id: 432 }
          - { vlan_id: 433 }
          - { vlan_id: 434 }
          - { vlan_id: 435 }
          - { vlan_id: 436 }
          - { vlan_id: 437 }
          - { vlan_id: 438 }
          - { vlan_id: 439 }
          - { vlan_id: 440 }
          - { vlan_id: 441 }
          - { vlan_id: 442 }
          - { vlan_id: 443 }
          - { vlan_id: 444 }
          - { vlan_id: 445 }
          - { vlan_id: 446 }
          - { vlan_id: 447 }
          - { vlan_id: 448 }
          - { vlan_id: 449 }
          - { vlan_id: 450 }
          - { vlan_id: 451 }
          - { vlan_id: 452 }
          - { vlan_id: 453 }
          - { vlan_id: 454 }
          - { vlan_id: 455 }
          - { vlan_id: 456 }
          - { vlan_id: 457 }
          - { vlan_id: 458 }
          - { vlan_id: 459 }
          - { vlan_id: 460 }
          - { vlan_id: 461 }
          - { vlan_id: 462 }
          - { vlan_id: 463 }
          - { vlan_id: 464 }
          - { vlan_id: 465 }
          - { vlan_id: 466 }
          - { vlan_id: 467 }
          - { vlan_id: 468 }
          - { vlan_id: 469 }
          - { vlan_id: 470 }
          - { vlan_id: 471 }
          - { vlan_id: 472 }
          - { vlan_id: 473 }
          - { vlan_id: 474 }
          - { vlan_id: 475 }
          - { vlan_id: 476 }
          - { vlan_id: 477 }
          - { vlan_id: 478 }
          - { vlan_id: 479 }
          - { vlan_id: 480 }
          - { vlan_id: 481 }
          - { vlan_id: 482 }
          - { vlan_id: 483 }
          - { vlan_id: 484 }
          - { vlan_id: 485 }
          - { vlan_id: 486 }
          - { vlan_id: 487 }
          - { vlan_id: 488 }
          - { vlan_id: 489 }
          - { vlan_id: 490 }
          - { vlan_id: 491 }
          - { vlan_id: 492 }
          - { vlan_id: 493 }
          - { vlan_id: 494 }
          - { vlan_id: 495 }
          - { vlan_id: 496 }
          - { vlan_id: 497 }
          - { vlan_id: 498 }
          - { vlan_id: 499 }
          - { vlan_id: 500 }
