---
- name: Register RHEL content host to Red Hat Satellite
  hosts: redhat 
  become: true

  tasks:
    - name: 'Install bootstrap rpm'
      yum:
        name: "http://satellite.mlab.com/pub/katello-ca-consumer-latest.noarch.rpm"
        state: "present"

    - name: 'Register client with subscription-manager'
      redhat_subscription:
        state: "present"
        activationkey: 7.4
