---
- name: intranet services
  hosts: servera.lab.example.com
  become: yes
  tasks:
    - block:
      - name: latest httpd version installed
        yum:
          name: httpd
          state: latest
      - name: latest firewalld version installed
        yum: 
          name: firewalld
          state: latest
    - block: 
      - name: firewalld permits http service
        firewalld:
          service: http
          permanent: true
          state: enabled
          immediate: yes
    - block:
      - name: httpd enabled and running
        service:
          name: httpd
          enabled: true
          state: started
      - name: firewalld enabled and running
        service: 
          name: firewalld
          enabled: true
          state: started
    - block: 
      - name: test html page
        copy: 
          content: "Welcome to the example.com intranet!\n"
          dest: /var/www/html/index.html

- name: test
  hosts: localhost
  tasks:
    - name: connect to intranet
      uri: 
        url: http://servera.lab.example.com
        status_code: 200

