- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group_name }}"
      name: "{{ subnet_name }}"
      address_prefix: "{{ subnet_prefix }}"
      virtual_network: "{{ virtual_network_name }}"