- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ resource_group_name }}"
      name: "{{ vnic_name }}"
      virtual_network: "{{ virtual_network_name }}"
      subnet: "{{ subnet_name }}"
      public_ip_name: "{{ public_IP_name }}"
      security_group: "{{ network_security_group_name }}"