---
# it may make sense to provide these at the host vars level
ansible_centos_user: azureuser

ansible_rhel_user: cloud-user

# Java 8 recommended
# Full JDK (not just JRE) recommended. See https://access.redhat.com/solutions/18259
eap_java_pkg_name: java-1.8.0-openjdk-devel

# Override the default method. See https://github.com/rhtconsulting/jboss_eap/blob/master/README.md
transfer_method: csp-to-host  #csp-to-host | copy-from-controller | file-server-to-host

# Here are variables related to the standalone JBoss installation

http_port: 8080
https_port: 8443

# AWS specific variables
ec2_access_key:
ec2_secret_key:
ec2_region: us-east-1
ec2_zone:
ec2_image: ami-6c1e8f04
ec2_instance_type: m1.small
ec2_keypair: djohnson
ec2_security_group: default
ec2_instance_count: 3
ec2_tag: demo
ec2_tag_name_prefix: dj
ec2_hosts: all
wait_for_port: 22

# This user name will be set by Tower, when run through Tower
tower_user_name: admin
