---
- name: Enable Features
  tags: [api, nxapi, hsrp]
  with_items:
    - hsrp
  nxos_feature:
    provider: "{{provider}}"
    feature: "{{ item }}"
    state: enabled

- name: Configure HSRP
  tags: [api, nxapi, hsrp]
  with_items: "{{ hsrp.interfaces }}"
  nxos_hsrp:
    provider: "{{provider}}"
    group: "{{ item.group }}"
    vip: "{{ item.vip }}"
    interface: "{{ item.interface }}"
