---

- hosts: all
  become: true
  gather_facts: true
  become_user: azureuser
  ansible_ssh_user: azureuser

  vars:
    - name: "{{ rhn_username }}"
    - name: "{{ rhn_password }}"

  roles:
    - redhat-cop.jboss_common
    - redhat-cop.jboss_eap
