---

- hosts: jboss_datagrid_rhel_hosts
  become_user: "{{ ansible_rhel_user }}"
  become: true
  gather_facts: true
  vars:
    disable_firewall: false

  vars_prompt:
    - name: "rhn_username"
      prompt: "Enter Your Red Hat Customer Portal Username"
      private: no

    - name: "rhn_password"
      prompt: "Enter Your Red Hat Customer Portal Password"
      private: yes

  roles:
    - redhat-cop.jboss_common
    - redhat-cop.jboss_datagrid
