---
- name: Configure VLANs
  tags: [api, nxapi, vlan]
  loop_control:
    pause: 1
  with_items: "{{ vlans }}"
  nxos_vlan:
    provider: "{{provider}}"
    vlan_id: "{{ item.id }}"
    name: "{{ item.name }}"
