---
##
# As the JBoss Data Grid service would be named like jboss-as-standlone.sh or jboss-eap.sh
# the service ( directed via systemctl ) requires the service name to be without
# extension hence we use spiltext filter to get the service name wihout '.sh' extension
##
- name: Restart jboss datagrid Service
  become: true
  service:
    name: "{{ jboss_datagrid_service_name }}"
    state: restarted
  tags:
    - jboss_eap

# Sanity test if everything was setup right and JBoss is running
- name: Verify jboss datagrid is running
  wait_for: port="11222" host="{{ jboss_datagrid_bind_web_address }}" timeout=120
  notify: Check jboss datagrid is available

- name: Check jboss datagrid is available
  uri:
    url: "http://{{jboss_datagrid_bind_web_address}}:11222"

